apiVersion: apps/v1 
kind: Deployment 
metadata:
  namespace: es 
  name: analytics  
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: analytics
  template: 
    metadata: 
      labels: 
        app: analytics 
        service: analytics
    spec:
      containers:
        - name: analytics
          image: registry.gitlab.com/kdg-ti/integratieproject-2/teams/team-5/monopoly.analytics:latest
          imagePullPolicy: Always
          name: analytics
          env:
            - name: elasticsearchUrl
              value: es-client:9200
            - name: elasticUsername
              value: elastic
            - name: elasticPassword
              value: w6HfdzyRBeb0OsOQxdGo
          ports: 
            - containerPort: 6969
            - containerPort: 5672
              name: rabbit
      imagePullSecrets:
        - name: kibana-secret
 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: analytics
  namespace: es
  labels:
    service: analytics 
spec: 
  ports: 
  - port: 6969
    name: microservice
  - port: 5672
    name: rabbit
  selector: 
    name: analytics
